workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
    scripts:
      - name: Gerar estrutura nativa do Android automaticamente
        script: |
          flutter create . --platforms=android
      - name: Obter pacotes do pubspec
        script: |
          flutter pub get
      - name: Compilar o APK Release
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
