workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
      groups:
        - env_vars    # <--- Mete aqui o nome do grupo que criaste no painel do Codemagic
    scripts:
      - name: Gerar estrutura nativa do Android automaticamente
        script: |
          flutter create . --platforms=android
      - name: Injetar permissão de Internet automaticamente
        script: |
          python3 - << 'EOF'
          path = "android/app/src/main/AndroidManifest.xml"
          try:
              with open(path, "r") as f:
                  content = f.read()
              if "android.permission.INTERNET" not in content:
                  content = content.replace("<application", "<uses-permission android:name=\"android.permission.INTERNET\"/>\n    <application")
                  with open(path, "w") as f:
                      f.write(content)
              print("Permissão injetada com sucesso!")
          except Exception as e:
              print(f"Erro ao injetar permissão: {e}")
          EOF
      - name: Obter pacotes do pubspec
        script: |
          flutter pub get
      - name: Compilar o APK Release
        script: |
          flutter build apk --release --dart-define=DATABASE_URL=$DATABASE_URL
    artifacts:
      - build/**/outputs/**/*.apk
